(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';(class{constructor(a,b){this.g=b===f?a:""}}).prototype.toString=function(){return this.g.toString()};var f={};function g(a,b,d){a.addEventListener&&a.addEventListener(b,d,!1)};function h(a,b,d){if(Array.isArray(b))for(var c=0;c<b.length;c++)h(a,String(b[c]),d);else null!=b&&d.push(a+(""===b?"":"="+encodeURIComponent(String(b))))};function k(a,b,d=null){l(a,b,d)}function l(a,b,d){a.google_image_requests||(a.google_image_requests=[]);const c=a.document.createElement("img");if(d){const e=B=>{d&&d(B);c.removeEventListener&&c.removeEventListener("load",e,!1);c.removeEventListener&&c.removeEventListener("error",e,!1)};g(c,"load",e);g(c,"error",e)}c.src=b;a.google_image_requests.push(c)};function m(a=null){return a&&"22"===a.getAttribute("data-jc")?a:document.querySelector('[data-jc="22"]')};var n=document,p=window;var q={};function r(){if(q!==q)throw Error("Bad secret");};function t(){var a="undefined"!==typeof window?window.trustedTypes:void 0;return null!==a&&void 0!==a?a:null};var u,v=class{};class w extends v{constructor(){var a=null!==x&&void 0!==x?x:"";super();r();this.g=a}toString(){return this.g.toString()}}var x=null===(u=t())||void 0===u?void 0:u.emptyHTML;new w;var y,z=class{};class A extends z{constructor(){var a=null!==C&&void 0!==C?C:"";super();r();this.g=a}toString(){return this.g.toString()}}var C=null===(y=t())||void 0===y?void 0:y.emptyScript;new A;var D=class{};class E extends D{constructor(a){super();r();this.g=a}toString(){return this.g}}new E("about:blank");new E("about:invalid#zTSz");function F(a){g(n,a.j,()=>{if(n[a.g])a.h&&(a.h=!1,a.i=Date.now(),G(a,0));else{if(-1!=a.i){const b=Date.now()-a.i;0<b&&(a.i=-1,G(a,1,b))}G(a,3)}})}function H(a){g(p,"click",b=>a.handleClick(b))} 
function G(a,b,d){var c={gqid:a.m,qqid:a.o};0==b&&(c["return"]=0);1==b&&(c["return"]=1,c.timeDelta=d);2==b&&(c.bgload=1);3==b&&(c.fg=1);b=[];for(var e in c)h(e,c[e],b);k(p,a.l+"&label=window_focus&"+b.join("&"),void 0);if(!(.01<Math.random())){a=(a=m(document.currentScript))&&a.getAttribute("data-jc-version")||"unknown";a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${22}&version=${a}&sample=${.01}`;c=window;if(e=c.navigator)e=c.navigator.userAgent,e=/Chrome/.test(e)&&!/Edge/.test(e)? 
!0:!1;e&&c.navigator.sendBeacon?c.navigator.sendBeacon(a):k(c,a)}} 
class I{constructor(){var a=J.url,b=J["gws-id"],d=J["qem-id"];"undefined"!==typeof n.hidden?(this.g="hidden",this.j="visibilitychange"):"undefined"!==typeof n.mozHidden?(this.g="mozHidden",this.j="mozvisibilitychange"):"undefined"!==typeof n.msHidden?(this.g="msHidden",this.j="msvisibilitychange"):"undefined"!==typeof n.webkitHidden&&(this.g="webkitHidden",this.j="webkitvisibilitychange");this.l=a;this.h=!1;this.i=-1;this.m=b;this.o=d;n[this.g]&&G(this,2);F(this);H(this)}handleClick(){this.h=!0;p.setTimeout(()=> 
{this.h=!1},5E3)}};{const a=m(document.currentScript);if(null==a)throw Error("JSC not found 22");var J;{const b={},d=a.attributes;for(let c=d.length-1;0<=c;c--){const e=d[c].name;0===e.indexOf("data-jcp-")&&(b[e.substring(9)]=d[c].value)}J=b}window.window_focus_for_click=new I};}).call(this);
