* Stuff you don't need to emulate
- The cache in general
- The CACHE instruction
- The 5-stage pipeline
- The RDRAM/RDRAM Interface registers
* The CPU always runs in Kernel Mode.
- registers are always 64 bit
- 64 bit mips instructions are always available
- USE THE "64" SECTION IN THE MIPS MANUAL, ALWAYS!
- COP0 is always enabled, no matter the setting in the status register
* Virtual vs. Physical Addresses
- All operations on the CPU use "virtual addresses."
- In hardware, all reads go through Coprocessor0.
** Virtual Memory Regions
*** KSEG0 (0x80000000 - 0x9FFFFFFF)
- Subtract the beginning of the KSEG0 section (0x80000000) to get the physical address
*** KSEG1 (0xA0000000 - 0xBFFFFFFF)
- Subtract the beginning of the KSEG1 section (0xA0000000) to get the physical address
*** KSSEG (0xC0000000 - 0xDFFFFFFF)
- TODO
*** KSEG3 (0xE0000000 - 0xFFFFFFFF)
- TODO
* Floating point registers
In hardware, there are 32 of them. They are 64 bits wide.

They are called FGRXX in hardware, from 0 to 31.

When accessed through software, they are called FPRXX.

There is a bit in the status register, FR.

** When FR is off
The upper 32 bits of each FGR (FGR = hardware, remember) register become inaccessible.

The odd numbered FPRs become inaccessible (UNDEFINED BEHAVIOR, not an exception) and the even numbers become "virtual" - i.e,

- FPR0 is made up of <low 32bits of FGR1><low 32bits of FGR0>
- FPR2 is made up of <low 32bits of FGR3><low 32bits of FGR2>
- etc
** When FR is on
All 32 64 bit registers are fully accessible, including  their upper bits.
